### ISSUE TITLE
Documentation describes data parameter in callback as string when it will be object

### ISSUE THREAD

**Issue by spikyjt** [arthurlacoste/tampa#1]
In the documentation for `yamlParseString` and `yamlParseFile` the `data` parameter in the callback is described as:

> data {string} Return a string with everything replaced.

However, this is actually an object in this case. I presume this is a copy and paste error from the plain string parsing method?

**Comment by arthurlacoste** [comment]
Yes, its true ! data return an object ! This is a copy paste error.
